spring.application.name=cartservicechallenge

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONSOLE H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# SQL FORMAT
spring.jpa.properties.hibernate.format_sql=true

# EXECUTE data.sql AT START
spring.jpa.defer-datasource-initialization=true

# ===============================
# SQL INIT (data.sql)
# ===============================
spring.sql.init.mode=always
