spring.application.name=cartservicechallenge

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# CONSOLE H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=off
spring.jpa.open-in-view=false

# SQL FORMAT
spring.jpa.properties.hibernate.format_sql=false

# EXECUTE data.sql AT START
spring.jpa.defer-datasource-initialization=true

# ===============================
# SQL INIT (data.sql)
# ===============================
spring.sql.init.mode=always

# ===============================
# OBSERVABILITY (Prometheus + Graphana)
# ===============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
